before_install:
    - sudo apt-get -y install texlive texlive-lang-cyrillic texlive-xetex texlive-generic-extra texlive-fonts-extra texlive-science fonts-cmu fonts-lmodern 
install:
- pushd /opt/pyenv
- git branch --set-upstream-to=origin/master deploy
- git pull --ff-only
- git checkout v1.2.20
- pyenv install -v 3.7.8
- popd
script:
- python3 ./build.py
on:
  branch: main
deploy:
    provider: pages
    github_token: $GITHUB_TOKEN
    skip_cleanup: true
    repo: vsgol/hse-calculus-2.2
    target_branch: pdf
    local_dir: pdf
    
